# Student Activity: Reading Stocks Data from a CSV

## 1. Import the pandas library as _pd_

In [12]:
# initial imports
import pandas as pd

## 2. Create a dataframe reading a CSV file

In [13]:
# set the file path
file_path = "/home/training/Desktop/TechCatalyst_DE_2026/student-work/week2/Pandas Student Activities/01-Stu_Reading_CSVs/Resources/amd_stock_data.csv"

# create a Pandas dataframe from a csv file
df = pd.read_csv(file_path, header=None)

## 3. Exploring the data

In [14]:
# get the first 10 rows from the dataframe
df.head(10)

         0     1         2     3     4     5
0  4/29/09  3.51  11537950  3.40  3.56  3.38
1  4/30/09  3.61  18193730  3.55  3.73  3.53
2   5/1/09  3.82  16233940  3.55  3.90  3.55
3   5/4/09  4.26  21236940  3.90  4.30  3.83
4   5/5/09  4.32  16369170  4.36  4.39  4.11
5   5/6/09  4.31  15075630  4.45  4.45  4.12
6   5/7/09  4.01  23369680  4.22  4.35  3.91
7   5/8/09  3.93  14316080  4.12  4.15  3.84
8  5/11/09  4.22  25214610  3.90  4.37  3.87
9  5/12/09  4.35  29715910  4.41  4.50  4.13

## 4. Fixing column names

In [17]:
# set column names
# recreate the dataframe
# add columns names
df = df.rename(columns={0: "Date", 1: "Close", 2: "Volume", 3: "Open", 4: "High", 5: "Low"})

df.head()

      Date  Close    Volume  Open  High   Low
0  4/29/09   3.51  11537950  3.40  3.56  3.38
1  4/30/09   3.61  18193730  3.55  3.73  3.53
2   5/1/09   3.82  16233940  3.55  3.90  3.55
3   5/4/09   4.26  21236940  3.90  4.30  3.83
4   5/5/09   4.32  16369170  4.36  4.39  4.11

## 5. Get the first 10 rows

In [18]:
# get the first 10 rows from the dataframe
df.head(10)

      Date  Close    Volume  Open  High   Low
0  4/29/09   3.51  11537950  3.40  3.56  3.38
1  4/30/09   3.61  18193730  3.55  3.73  3.53
2   5/1/09   3.82  16233940  3.55  3.90  3.55
3   5/4/09   4.26  21236940  3.90  4.30  3.83
4   5/5/09   4.32  16369170  4.36  4.39  4.11
5   5/6/09   4.31  15075630  4.45  4.45  4.12
6   5/7/09   4.01  23369680  4.22  4.35  3.91
7   5/8/09   3.93  14316080  4.12  4.15  3.84
8  5/11/09   4.22  25214610  3.90  4.37  3.87
9  5/12/09   4.35  29715910  4.41  4.50  4.13

## 6. Get the bottom 10 rows

In [ ]:
# get the bottom 10 rows from the dataframe
df.tail(10)