### Import Libraries and Dependencies

In [8]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
%matplotlib inline

### Read CSV as Pandas DataFrame

In [9]:
# Read in csv
csv_path = Path("../Resources/tsla_google_finance.csv")
tsla_df = pd.read_csv(csv_path)
tsla_df.head()

       Date   Close
0  11/13/18  338.73
1  11/14/18  344.00
2  11/15/18  348.44
3  11/16/18  354.31
4  11/19/18  353.47

### Index Data by `Date`

In [10]:
# Set `Date` as index
tsla_date_index_df = tsla_df.set_index("Date")
tsla_date_index_df.head()

           Close
Date
11/13/18  338.73
11/14/18  344.00
11/15/18  348.44
11/16/18  354.31
11/19/18  353.47

### Assess and Clean Data

In [ ]:
# Check for nulls
tsla_date_index_df.isnull().sum()

# Drop missing values
tsla_drop_null = tsla_date_index_df.dropna()

# Validate no more missing values
tsla_drop_null.isnull().sum()

Close    0
dtype: int64

### Calculate Daily Returns

In [ ]:
# Calculate daily returns

### Sort the DataFrame by `Close` to Get Records with Top Daily Returns

In [ ]:
# Sort data by `Close` in descending order

### Slice Out 5 Records

In [ ]:
# Slice out top 5

### Plot Top 5 Performing Days for TSLA Daily Returns

In [ ]:
# Plot top 5 performing days

In [ ]:
# Alternatively, visualizing the returns as a bar chart: