In [65]:
# Import Dependencies
import pandas as pd

In [66]:
# Reference the file where the CSV is located
file_path = "/home/training/Desktop/TechCatalyst_DE_2026/student-work/week2/Pandas Student Activities/04-Par_CleaningApplianceData/Resources/dga_lpg.csv"

# Import the data into a Pandas DataFrame
df = pd.read_csv(file_path)

df.head()

,Part,Type,Type.1,Brand,牌子,Model,Other Information,其他資料,Place of Manufacture,製造地點,Applicant,申請人,Telephone Number,Approval Expiry Date
0,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,嵌入式單頭平面爐,De Dietrich,NaN,DTG1288XC,CERAMIC GLASS TOP PANEL,陶瓷玻璃面版,Italy,意大利,Gilman Group Limited,太平洋行國際有限公司,2418 3272,2023-09-26
1,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,嵌入式單頭平面爐,Electrolux,伊萊克斯,EGC-2901,CERAMIC GLASS TOP PANEL,陶瓷玻璃面版,The People's Republic of China,中華人民共和國,"Dah Chong Hong, Ltd.",大昌貿易行有限公司,2262 1690,2024-06-24
2,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,嵌入式單頭平面爐,Gaggenau,NaN,VG231120F,STAINLESS STEEL TOP PANEL,不銹鋼面版,France,法國,Kitchen Infinity Corp. Ltd.,Kitchen Infinity Corp. Ltd.,2552 2208,2024-04-01
3,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,嵌入式單頭平面爐,Gaggenau,NaN,VG231114F,STAINLESS STEEL TOP PANEL,不銹鋼面版,France,法國,Kitchen Infinity Corp. Ltd.,Kitchen Infinity Corp. Ltd.,2552 2208,2022-07-19
4,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,嵌入式單頭平面爐,GERMAN POOL,德國寶,GP12-1-LG,GLASS TOP PANEL,玻璃面版,The People's Republic of China,中華人民共和國,German Pool (Hong Kong) Ltd.,德國寶（香港）有限公司,2773 2812,2025-02-15

In [67]:
# Reduce to columns that are in English
df.columns

df = df.loc[:, ["Part", "Type", "Brand", "Model", "Other Information", "Place of Manufacture", "Applicant", "Telephone Number", "Approval Expiry Date"]]

df

,Part,Type,Brand,Model,Other Information,Place of Manufacture,Applicant,Telephone Number,Approval Expiry Date
0,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,De Dietrich,DTG1288XC,CERAMIC GLASS TOP PANEL,Italy,Gilman Group Limited,2418 3272,2023-09-26
1,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,Electrolux,EGC-2901,CERAMIC GLASS TOP PANEL,The People's Republic of China,"Dah Chong Hong, Ltd.",2262 1690,2024-06-24
2,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,Gaggenau,VG231120F,STAINLESS STEEL TOP PANEL,France,Kitchen Infinity Corp. Ltd.,2552 2208,2024-04-01
3,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,Gaggenau,VG231114F,STAINLESS STEEL TOP PANEL,France,Kitchen Infinity Corp. Ltd.,2552 2208,2022-07-19
4,Part 1 – Approved Domestic Gas Cooking Appliances,Built-in Hotplate 1 Burner,GERMAN POOL,GP12-1-LG,GLASS TOP PANEL,The People's Republic of China,German Pool (Hong Kong) Ltd.,2773 2812,2025-02-15
...,...,...,...,...,...,...,...,...,...
934,Part 5 – Approved Domestic Gas Appliances whic...,Room-sealed (fanned draught) gas water heater,Vatti,G12L-HK,TOP FLUE,The People's Republic of China,Vatti (H.K.) Limited,2620 1389,2010-09-13
935,Part 5 – Approved Domestic Gas Appliances whic...,Room-sealed (fanned draught) gas water heater,Vatti,G16L-HK,TOP FLUE,The People's Republic of China,Vatti (H.K.) Limited,2620 1389,2010-09-13
936,Part 5 – Approved Domestic Gas Appliances whic...,Room-sealed (natural draught) gas water heater,Junkers,J10BF1,NOT APPLICABLE,Portugal,"Jebsen & Co., Ltd.",2923 8440,2005-06-06
937,Part 5 – Approved Domestic Gas Appliances whic...,Room-sealed (natural draught) gas water heater,Junkers,WR225-1AV1B31S2704,NOT APPLICABLE,Portugal,"Jebsen & Co., Ltd.",2923 8440,2005-06-11
938,Part 5 – Approved Domestic Gas Appliances whic...,Room-sealed (natural draught) gas water heater,Junkers,WR250-1AV1B31S2704,NOT APPLICABLE,Portugal,"Jebsen & Co., Ltd.",2923 8440,2005-06-11

In [68]:
# look for missing values
df.isnull().sum()

Part                    0
Type                    0
Brand                   0
Model                   0
Other Information       3
Place of Manufacture    0
Applicant               0
Telephone Number        0
Approval Expiry Date    0
dtype: int64

In [69]:
# drop null rows
df = df.dropna()

In [70]:
# verify counts
df.isnull().sum()

Part                    0
Type                    0
Brand                   0
Model                   0
Other Information       0
Place of Manufacture    0
Applicant               0
Telephone Number        0
Approval Expiry Date    0
dtype: int64

In [71]:
# Check to see if there are any values with mispelled or similar values in "Applicant"
df = df.sort_values(by="Applicant")

df["Applicant"].unique()

<ArrowStringArray>
[                            'A & P International Ltd',
                    'Alliance Ascent Holdings Limited',
                                'Alpha Appliances Ltd',
                         'Araytron Technology Limited',
                            'BSH Home Appliances Ltd.',
                               'Baumatic Asia Limited',
          'Best Joint International Trading Co., Ltd.',
                     'Bright Gas Appliances Co., Ltd.',
                 'California Heavy Industries Limited',
                               'Charm Vantage Limited',
                                'Chuen Kwong Hong Ltd',
         'Crown Gas Stoves (Holdings) Company Limited',
                          'Crown Gas Stoves Co., Ltd.',
                         'D & A Electronics Co., Ltd.',
                                'Dah Chong Hong, Ltd.',
                        'Dong Woo Industrial Co. Ltd.',
                      'Energy Trading Company Limited',
              'Excellent Industry (Hong Kong) Limited',
                    'Famous International (H.K.) Ltd.',
                               'Federal Supplier Ltd.',
               'Fidelity (Far East) Trading Co., Ltd.',
 'Fortress - Adivision of A.S. Watson Group (HK) Ltd.',
                             'Fung Lee (Asia) Limited',
                          'GMG International co. Ltd.',
                        'Gastar Group Company Limited',
                       'General Appliance (H.K.) Ltd.',
                        'German Pool (Hong Kong) Ltd.',
                                'Gilman Group Limited',
                   'Great Treasure International Ltd.',
                          'Hibachi Gas Cooker Limited',
                       'Homepro International Limited',
                  'Hong Kong L.P. Gas (Holdings) Ltd.',
                                        'Hop Hing Co.',
                          'Hotpool Industries Limited',
             'Iwatani Corporation (Hong Kong) Limited',
                                  'Jebsen & Co., Ltd.',
                         'K & K Trading (H.K) Limited',
                    'Kelvin Electric Trading Co. Ltd.',
                         'Kitchen Infinity Corp. Ltd.',
                       'Lighting (Japan) Trading Ltd.',
                     'Lighting Gas Stoves Trading Ltd',
                           'Lung Shing Cheung Hop Kee',
                         'Madison (Hong Kong) Limited',
                           'Miele (Hong Kong) Limited',
                           'Nan Kee Trading Co., Ltd.',
                       'Nasim Engineering Trading Co.',
       'Perfect Gas Stoves Trading & Engineering Ltd.',
    'Shun Hing Electric Works & Engineering Co., Ltd.',
                      'Silver Star International Ltd.',
           'Sun Hing Gas Household Utensils Co., Ltd.',
                                  'Sun Kee LP Gas Co.',
                          'Sun Kee LP Gas Co. Limited',
                               'Sunny Eternal Limited',
                       'Sunrise Enterprise HK Limited',
            'Tai Cheong International Trading Limited',
                                     'Teka China Ltd.',
                 'The Hong Kong & China Gas Co., Ltd.',
            'The Union Gas Appliances (Holdings) Ltd.',
                                'Tops Company Limited',
                                 'Toptech Co. Limited',
                                'Vatti (H.K.) Limited',
                                 'Vocci Group Limited',
                'Wai Bong Electrical Trading Co. Ltd.',
          'Wealthy Link International Trading Limited',
                            'Westwing Appliances Ltd.',
                               'Wetol Company Limited',
                              'Whampo Trading Limited',
                          'Whirlpool (Hong Kong) Ltd.',
            'Wing Hing Electrical Engineers Co., Ltd.',
                         'Wintex Asia Enterprise Ltd.',
                           'World Engineering Limited']
Length: 71, dtype: str

In [72]:
# Combine similar applicants together
applicant_mapping = {
    "Sun Kee LP Gas Co. Limited": "Sun Kee LP Gas Co."
}

df["Applicant"] = df["Applicant"].replace(applicant_mapping)

In [73]:
# Check to see if you combined similar applicants correctly in "Applicant"
df["Applicant"].unique()

<ArrowStringArray>
[                            'A & P International Ltd',
                    'Alliance Ascent Holdings Limited',
                                'Alpha Appliances Ltd',
                         'Araytron Technology Limited',
                            'BSH Home Appliances Ltd.',
                               'Baumatic Asia Limited',
          'Best Joint International Trading Co., Ltd.',
                     'Bright Gas Appliances Co., Ltd.',
                 'California Heavy Industries Limited',
                               'Charm Vantage Limited',
                                'Chuen Kwong Hong Ltd',
         'Crown Gas Stoves (Holdings) Company Limited',
                          'Crown Gas Stoves Co., Ltd.',
                         'D & A Electronics Co., Ltd.',
                                'Dah Chong Hong, Ltd.',
                        'Dong Woo Industrial Co. Ltd.',
                      'Energy Trading Company Limited',
              'Excellent Industry (Hong Kong) Limited',
                    'Famous International (H.K.) Ltd.',
                               'Federal Supplier Ltd.',
               'Fidelity (Far East) Trading Co., Ltd.',
 'Fortress - Adivision of A.S. Watson Group (HK) Ltd.',
                             'Fung Lee (Asia) Limited',
                          'GMG International co. Ltd.',
                        'Gastar Group Company Limited',
                       'General Appliance (H.K.) Ltd.',
                        'German Pool (Hong Kong) Ltd.',
                                'Gilman Group Limited',
                   'Great Treasure International Ltd.',
                          'Hibachi Gas Cooker Limited',
                       'Homepro International Limited',
                  'Hong Kong L.P. Gas (Holdings) Ltd.',
                                        'Hop Hing Co.',
                          'Hotpool Industries Limited',
             'Iwatani Corporation (Hong Kong) Limited',
                                  'Jebsen & Co., Ltd.',
                         'K & K Trading (H.K) Limited',
                    'Kelvin Electric Trading Co. Ltd.',
                         'Kitchen Infinity Corp. Ltd.',
                       'Lighting (Japan) Trading Ltd.',
                     'Lighting Gas Stoves Trading Ltd',
                           'Lung Shing Cheung Hop Kee',
                         'Madison (Hong Kong) Limited',
                           'Miele (Hong Kong) Limited',
                           'Nan Kee Trading Co., Ltd.',
                       'Nasim Engineering Trading Co.',
       'Perfect Gas Stoves Trading & Engineering Ltd.',
    'Shun Hing Electric Works & Engineering Co., Ltd.',
                      'Silver Star International Ltd.',
           'Sun Hing Gas Household Utensils Co., Ltd.',
                                  'Sun Kee LP Gas Co.',
                               'Sunny Eternal Limited',
                       'Sunrise Enterprise HK Limited',
            'Tai Cheong International Trading Limited',
                                     'Teka China Ltd.',
                 'The Hong Kong & China Gas Co., Ltd.',
            'The Union Gas Appliances (Holdings) Ltd.',
                                'Tops Company Limited',
                                 'Toptech Co. Limited',
                                'Vatti (H.K.) Limited',
                                 'Vocci Group Limited',
                'Wai Bong Electrical Trading Co. Ltd.',
          'Wealthy Link International Trading Limited',
                            'Westwing Appliances Ltd.',
                               'Wetol Company Limited',
                              'Whampo Trading Limited',
                          'Whirlpool (Hong Kong) Ltd.',
            'Wing Hing Electrical Engineers Co., Ltd.',
                         'Wintex Asia Enterprise Ltd.',
                           'World Engineering Limited']
Length: 70, dtype: str

In [75]:
# Create a new DataFrame that looks into a specific Place of Manufacture
df.columns

df = df["Place of Manufacture"]

df.head()

540                             Korea
278    The People's Republic of China
279    The People's Republic of China
304                         Australia
642    The People's Republic of China
Name: Place of Manufacture, dtype: str